//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.data.v1;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openclinica.ws.data.v1 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ImportRequest_QNAME = new QName("http://openclinica.org/ws/data/v1", "importRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openclinica.ws.data.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImportResponse }
     * 
     * @return
     *     the new instance of {@link ImportResponse }
     */
    public ImportResponse createImportResponse() {
        return new ImportResponse();
    }

    /**
     * Create an instance of {@link AuditMessagesType }
     * 
     * @return
     *     the new instance of {@link AuditMessagesType }
     */
    public AuditMessagesType createAuditMessagesType() {
        return new AuditMessagesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://openclinica.org/ws/data/v1", name = "importRequest")
    public JAXBElement<Object> createImportRequest(Object value) {
        return new JAXBElement<>(_ImportRequest_QNAME, Object.class, null, value);
    }

}
