//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.studyeventdefinition.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.openclinica.ws.beans.StudyEventDefinitionListAllType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="studyEventDefinitionListAll" type="{http://openclinica.org/ws/beans}studyEventDefinitionListAllType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studyEventDefinitionListAll"
})
@XmlRootElement(name = "listAllRequest")
public class ListAllRequest {

    @XmlElement(required = true)
    protected StudyEventDefinitionListAllType studyEventDefinitionListAll;

    /**
     * Gets the value of the studyEventDefinitionListAll property.
     * 
     * @return
     *     possible object is
     *     {@link StudyEventDefinitionListAllType }
     *     
     */
    public StudyEventDefinitionListAllType getStudyEventDefinitionListAll() {
        return studyEventDefinitionListAll;
    }

    /**
     * Sets the value of the studyEventDefinitionListAll property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyEventDefinitionListAllType }
     *     
     */
    public void setStudyEventDefinitionListAll(StudyEventDefinitionListAllType value) {
        this.studyEventDefinitionListAll = value;
    }

}
