//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.studysubject.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.openclinica.ws.beans.StudySubjectType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="studySubject" type="{http://openclinica.org/ws/beans}studySubjectType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studySubject"
})
@XmlRootElement(name = "isStudySubjectRequest")
public class IsStudySubjectRequest {

    @XmlElement(required = true)
    protected StudySubjectType studySubject;

    /**
     * Gets the value of the studySubject property.
     * 
     * @return
     *     possible object is
     *     {@link StudySubjectType }
     *     
     */
    public StudySubjectType getStudySubject() {
        return studySubject;
    }

    /**
     * Sets the value of the studySubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudySubjectType }
     *     
     */
    public void setStudySubject(StudySubjectType value) {
        this.studySubject = value;
    }

}
