//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.study.v1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.openclinica.ws.beans.SiteRefType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="studyMetadata" type="{http://openclinica.org/ws/beans}siteRefType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "studyMetadata"
})
@XmlRootElement(name = "getMetadataRequest")
public class GetMetadataRequest {

    @XmlElement(required = true)
    protected SiteRefType studyMetadata;

    /**
     * Gets the value of the studyMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link SiteRefType }
     *     
     */
    public SiteRefType getStudyMetadata() {
        return studyMetadata;
    }

    /**
     * Sets the value of the studyMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link SiteRefType }
     *     
     */
    public void setStudyMetadata(SiteRefType value) {
        this.studyMetadata = value;
    }

}
