//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.study.v1;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openclinica.ws.study.v1 package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ListAllRequest_QNAME = new QName("http://openclinica.org/ws/study/v1", "listAllRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openclinica.ws.study.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListAllResponse }
     * 
     * @return
     *     the new instance of {@link ListAllResponse }
     */
    public ListAllResponse createListAllResponse() {
        return new ListAllResponse();
    }

    /**
     * Create an instance of {@link GetMetadataRequest }
     * 
     * @return
     *     the new instance of {@link GetMetadataRequest }
     */
    public GetMetadataRequest createGetMetadataRequest() {
        return new GetMetadataRequest();
    }

    /**
     * Create an instance of {@link GetMetadataResponse }
     * 
     * @return
     *     the new instance of {@link GetMetadataResponse }
     */
    public GetMetadataResponse createGetMetadataResponse() {
        return new GetMetadataResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://openclinica.org/ws/study/v1", name = "listAllRequest")
    public JAXBElement<Object> createListAllRequest(Object value) {
        return new JAXBElement<>(_ListAllRequest_QNAME, Object.class, null, value);
    }

}
