//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.beans;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for crfsType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="crfsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="crf" type="{http://openclinica.org/ws/beans}crfObjType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crfsType", propOrder = {
    "crf"
})
public class CrfsType {

    protected CrfObjType crf;

    /**
     * Gets the value of the crf property.
     * 
     * @return
     *     possible object is
     *     {@link CrfObjType }
     *     
     */
    public CrfObjType getCrf() {
        return crf;
    }

    /**
     * Sets the value of the crf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrfObjType }
     *     
     */
    public void setCrf(CrfObjType value) {
        this.crf = value;
    }

}
