//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.beans;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for eventDefinitionCrfsType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="eventDefinitionCrfsType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="eventDefinitionCrf" type="{http://openclinica.org/ws/beans}eventDefinitionCrfType" maxOccurs="unbounded" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventDefinitionCrfsType", propOrder = {
    "eventDefinitionCrf"
})
public class EventDefinitionCrfsType {

    protected List<EventDefinitionCrfType> eventDefinitionCrf;

    /**
     * Gets the value of the eventDefinitionCrf property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventDefinitionCrf property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getEventDefinitionCrf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventDefinitionCrfType }
     * </p>
     * 
     * 
     * @return
     *     The value of the eventDefinitionCrf property.
     */
    public List<EventDefinitionCrfType> getEventDefinitionCrf() {
        if (eventDefinitionCrf == null) {
            eventDefinitionCrf = new ArrayList<>();
        }
        return this.eventDefinitionCrf;
    }

}
