//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.beans;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for eventDefinitionCrfType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="eventDefinitionCrfType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="required" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="doubleDataEntry" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="passwordRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="hideCrf" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="participantForm" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="allowAnonymousSubmission" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="submissionUrl" type="{http://openclinica.org/ws/beans}customStringType"/>
 *         <element name="offline" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         <element name="sourceDataVerificaiton" type="{http://openclinica.org/ws/beans}customStringType"/>
 *         <element name="crf" type="{http://openclinica.org/ws/beans}crfObjType"/>
 *         <element name="defaultCrfVersion" type="{http://openclinica.org/ws/beans}crfVersionType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "eventDefinitionCrfType", propOrder = {
    "required",
    "doubleDataEntry",
    "passwordRequired",
    "hideCrf",
    "participantForm",
    "allowAnonymousSubmission",
    "submissionUrl",
    "offline",
    "sourceDataVerificaiton",
    "crf",
    "defaultCrfVersion"
})
public class EventDefinitionCrfType {

    protected boolean required;
    protected boolean doubleDataEntry;
    protected boolean passwordRequired;
    protected boolean hideCrf;
    protected boolean participantForm;
    protected boolean allowAnonymousSubmission;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String submissionUrl;
    protected boolean offline;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String sourceDataVerificaiton;
    @XmlElement(required = true)
    protected CrfObjType crf;
    @XmlElement(required = true)
    protected CrfVersionType defaultCrfVersion;

    /**
     * Gets the value of the required property.
     * 
     */
    public boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     */
    public void setRequired(boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the doubleDataEntry property.
     * 
     */
    public boolean isDoubleDataEntry() {
        return doubleDataEntry;
    }

    /**
     * Sets the value of the doubleDataEntry property.
     * 
     */
    public void setDoubleDataEntry(boolean value) {
        this.doubleDataEntry = value;
    }

    /**
     * Gets the value of the passwordRequired property.
     * 
     */
    public boolean isPasswordRequired() {
        return passwordRequired;
    }

    /**
     * Sets the value of the passwordRequired property.
     * 
     */
    public void setPasswordRequired(boolean value) {
        this.passwordRequired = value;
    }

    /**
     * Gets the value of the hideCrf property.
     * 
     */
    public boolean isHideCrf() {
        return hideCrf;
    }

    /**
     * Sets the value of the hideCrf property.
     * 
     */
    public void setHideCrf(boolean value) {
        this.hideCrf = value;
    }

    /**
     * Gets the value of the participantForm property.
     * 
     */
    public boolean isParticipantForm() {
        return participantForm;
    }

    /**
     * Sets the value of the participantForm property.
     * 
     */
    public void setParticipantForm(boolean value) {
        this.participantForm = value;
    }

    /**
     * Gets the value of the allowAnonymousSubmission property.
     * 
     */
    public boolean isAllowAnonymousSubmission() {
        return allowAnonymousSubmission;
    }

    /**
     * Sets the value of the allowAnonymousSubmission property.
     * 
     */
    public void setAllowAnonymousSubmission(boolean value) {
        this.allowAnonymousSubmission = value;
    }

    /**
     * Gets the value of the submissionUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubmissionUrl() {
        return submissionUrl;
    }

    /**
     * Sets the value of the submissionUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubmissionUrl(String value) {
        this.submissionUrl = value;
    }

    /**
     * Gets the value of the offline property.
     * 
     */
    public boolean isOffline() {
        return offline;
    }

    /**
     * Sets the value of the offline property.
     * 
     */
    public void setOffline(boolean value) {
        this.offline = value;
    }

    /**
     * Gets the value of the sourceDataVerificaiton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceDataVerificaiton() {
        return sourceDataVerificaiton;
    }

    /**
     * Sets the value of the sourceDataVerificaiton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceDataVerificaiton(String value) {
        this.sourceDataVerificaiton = value;
    }

    /**
     * Gets the value of the crf property.
     * 
     * @return
     *     possible object is
     *     {@link CrfObjType }
     *     
     */
    public CrfObjType getCrf() {
        return crf;
    }

    /**
     * Sets the value of the crf property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrfObjType }
     *     
     */
    public void setCrf(CrfObjType value) {
        this.crf = value;
    }

    /**
     * Gets the value of the defaultCrfVersion property.
     * 
     * @return
     *     possible object is
     *     {@link CrfVersionType }
     *     
     */
    public CrfVersionType getDefaultCrfVersion() {
        return defaultCrfVersion;
    }

    /**
     * Sets the value of the defaultCrfVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrfVersionType }
     *     
     */
    public void setDefaultCrfVersion(CrfVersionType value) {
        this.defaultCrfVersion = value;
    }

}
