//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.openclinica.ws.beans;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for listStudySubjectsInStudyType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="listStudySubjectsInStudyType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="studyRef" type="{http://openclinica.org/ws/beans}studyRefType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "listStudySubjectsInStudyType", propOrder = {
    "studyRef"
})
public class ListStudySubjectsInStudyType {

    @XmlElement(required = true)
    protected StudyRefType studyRef;

    /**
     * Gets the value of the studyRef property.
     * 
     * @return
     *     possible object is
     *     {@link StudyRefType }
     *     
     */
    public StudyRefType getStudyRef() {
        return studyRef;
    }

    /**
     * Sets the value of the studyRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link StudyRefType }
     *     
     */
    public void setStudyRef(StudyRefType value) {
        this.studyRef = value;
    }

}
